---
engines:
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 70
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "cleancode,design,naming,unusedcode"
  phpcodesniffer:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- .idea/
- tests/
- vendor/
- codeclimate-master/
