filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        too_many_arguments: true

coding_style:
    php:
        spaces:
            within:
                brackets: true
build:
    nodes:
        analysis:
            project_setup:
                override: ['true']
            tests:
                override: [php-scrutinizer-run]

filter:
    excluded_paths:
        - tests/*

tools:
    external_code_coverage: true
