language: php

php:
  - 7.0

before_install:
  - composer require satooshi/php-coveralls:dev-master
  - composer install

script:
  - mkdir -p tests/logs
  - phpunit --coverage-clover tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/logs/clover.xml
