language: phpt

php:
  - 7.0

before_install:
  - composer install

script:
  - mkdir -p tests/logs
  - phpunit --coverage-clover tests/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/logs/clover.xml
