language: php

php:
  - 7.0

before_install:
  - composer require satooshi/php-coveralls:dev-master
  - composer install

script:
  - phpunit --coverage-clover tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
